version: "3"
services:
  db:
    container_name: rate-db
    image: postgres:13.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql
      - dbstore:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    container_name: rate-api
    build:
      context: ./
      dockerfile: app_dockerfile
    depends_on:
            db:
             condition: service_healthy
    ports:
      - 3000:3000
volumes:
  dbstore:
    driver: local
